Detect unpublished packages
sholladay/squatter pull request #2
Opened 2018-08-28 06:36 UTC by bokub

Fixes #1 

I couldn't unpublish 'sunglasses', but I found 'leopard' to be unpublished too so I added it to the tests

2018-08-28 16:36 UTC, sholladay commented
I wonder what `meta` will look like for a package where a specific version was unpublished, rather than every version. The latter is npm's default, but you can specify a version in `npm unpublish`.

As for how to find a sample, perhaps `left-pad` still has older versions that are unpublished and were never restored.

2018-08-28 17:10 UTC, bokub commented
I've just tested, and here is the result: 
(I've unpublished the `0.0.1`)

```js
{
  // ...
  'dist-tags': { latest: '0.0.2' },
  versions:
   { '0.0.2':
      { //...
       }
   },
  time:
   { created: '2018-08-28T17:03:13.524Z',
     '0.0.1': '2018-08-28T17:03:13.692Z',
     modified: '2018-08-28T17:07:04.066Z',
     '0.0.2': '2018-08-28T17:06:04.272Z' },

```

2018-08-28 18:02 UTC, sholladay commented
Awesome, that's about what I would have expected.

The reason that matters is that squatter takes a second (currently undocumented) `version` argument. I'm not sure if there is a strong use case for it, but I implemented it so that i could use it in the tests if it turned out that the integration tests were too flakey, since they use the `latest` of real packages and someone could publish a new version that breaks those tests at any time. So far that has never been a problem, but I'm keeping an eye on it.

Anyway, in order to handle the `version` argument correctly, I guess `unpublished()` would have to first resolve the version using `dist-tags` (but handle it not existing) and then check if that version exists in `Object.keys(meta.versions)`. Based on the output you posted in the issue, it seems like when all versions are unpublished, they move `meta.versions` to `meta.time.unpublushed.versions`. So I suppose it would have to handle that, too.

Or to simplify everything, we could get rid of the `version` argument.

2018-08-29 08:50 UTC, sholladay commented
As the owner, you can choose to unpublish all versions or only some versions. The default behavior when you run `npm unpublish` is to unpublish all versions, but people can choose to unpublish specific versions if they feel like it (e.g. `0.0.2` had a major security flaw, but `0.0.3` has the fix, and you want to unpublish _only_ `0.0.2` to ensure no one is affected by the security flaw).

So unpublishing depends upon versioning in the same way that publishing does. The only part I'm not super familiar with is how they represent this in the registry data. I'll help investigate that and see if there is a way for us to tell that a specific version was unpublished or whether the entire namespace was unpublished. Give me a few days and I'll look into it!

2018-11-25 19:08 UTC, brekk commented
Any follow-up on this? I recently was using `npm-name-cli` which uses `squatter` as a dependency -- I was looking to publish `zark` but as far as I can tell from the registry it is unpublished / squatted upon by the user `~zark`:

```sh
npm-name zark
⠇ Checking name on npmjs.com…
```
Sat and hung for a while, until I hit Ctrl-C and then I saw:
```
^CTypeError: Cannot read property 'latest' of undefined
    at versionPkg (/[...]/.config/yarn/global/node_modules/squatter/lib/get-package.js:9:36)
    at squatter ([...[/.config/yarn/global/node_modules/squatter/index.js:42:17)
    at process._tickCallback (internal/process/next_tick.js:68:
```

I'd love to be able to use `npm-name` / `squatter` to track this status.

2018-11-25 20:31 UTC, sholladay commented
I will be fixing this, for sure. Most likely merging this PR as-is. I just need to find the time to verify my assumptions about the registry data are correct. Tentatively thinking I should be able to do that middle of this week. Soon as this is done, I will make a patch release. Thanks for your patience. :)

2018-12-15 07:05 UTC, laggingreflex commented
@brekk That error is probably fixed by https://github.com/sindresorhus/npm-name-cli/pull/15

2019-02-23 19:31 UTC, ctexxx commented
any updates on this? @sholladay

2019-04-29 14:17 UTC, sholladay requested changes

2019-04-29 14:17 UTC, sholladay commented on package.json
> +    "version": "0.2.1",
Could you please either undo this change or give me write access to your fork so I can do it for you? (I'll bump the version during the release process.)

2019-04-29 14:18 UTC, sholladay commented
Hi! I finally got around to this. Ready to merge with that one tweak. Thanks for your patience. :)

2019-07-01 15:47 UTC, sindresorhus commented
@bokub Ping

2019-07-01 16:10 UTC, bokub commented
Hi Sindre
I can't edit my PR because I've deleted the fork a long time ago 🙃
Maybe @sholladay can make an edit before or after merging? 

If not, I'll make a new PR tomorrow when I'm around a computer

2019-07-01 16:54 UTC, sholladay commented
For some reason, GitHub will allow me to merge, but not edit. I presume this is because the fork was deleted.

Don't worry about recreating the fork. What I'll do is squash merge and then amend the commit on master.

Thanks for your work on this!

2019-07-02 08:31 UTC, bokub commented
I've duplicated this PR in #5 😊

2019-07-02 08:31 UTC, closed without merging

2019-07-22 11:10 UTC, bokub commented
@sholladay Ping 🙋

2019-07-22 14:58 UTC, sholladay commented
I merged PR #5. Thanks for your work. I am aiming to do a release next weekend, possibly sooner.

2019-10-18 03:58 UTC, sindresorhus commented
@sholladay Reminder about releasing.

2019-11-07 07:38 UTC, sholladay commented
This fix has been released. Thanks for your patience, y'all. I've been taking care of my father who is very sick. I'm behind on many things, but OSS keeps me going. :)